### ISSUE TITLE
Error when trying to open .dm3 file

### ISSUE THREAD

**Issue by JulioAzcarate** [bcolsen/diffraction-ring-profiler#4]
Hi ... I'm newer using "diffraction-ring-profile" ... this program is very well, ... good job!!

However, I have a problem to open .dm3 files. This is the error shown in console:

`/home/julio/Desktop dif-pdf_0009 .dm3 /home/julio/Desktop/dif-pdf_0009.dm3
{'acq_date': b'8/9/2018', 'acq_time': b'9:52:17 AM', 'name': b'FEI Tecnai', 'micro': b'', 'hv': b'200000.0', 'mag': b'220.00000000000003', 'mode': b'DIFFRACTION', 'operator': b'', 'specimen': b''} (0.019381428137421608, b'1/nm')
Traceback (most recent call last):
  File "diffraction_ring_profiler.py", line 776, in OnOpen
    self.openimage()
  File "diffraction_ring_profiler.py", line 800, in openimage
    self.img_contrast = (dm3f.contrastlimits[0] - dm3f.imagedata.min(), dm3f.contrastlimits[1] - dm3f.imagedata.min())
  File "/home/julio/Programas/Binarios/diffraction-ring-profiler-master/dm3lib_v120.py", line 738, in contrastlimits
    low = int(float(self.tags["%s.ImageDisplayInfo.LowLimit" % tag_root]))
KeyError: 'root.DocumentObjectList.0.ImageDisplayInfo.LowLimit'`

How can I solve this issue???

Thanks in advance

**Comment by bcolsen** [comment]
It seems like your instrument isn't setting the low constant limit in the .dm3 file.  

Can you share the .dm3? 

I think you can attach it here in a zip file.

**Comment by JulioAzcarate** [comment]
Hi @bcolsen ... thank for your time.
I couldn't find for attach a file here, but I linking the [zipped .dm3](https://drive.google.com/open?id=1Gnf5TQslQ7ASmOgttwqMkNfBAAqv1c_q) file to download it.

Thanks in advance.
